//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClothProduct
    {
        public int ProductId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.Guid> Createdby { get; set; }
        public Nullable<System.Guid> Updatedby { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<System.DateTime> Updateddate { get; set; }
        public string ProductName { get; set; }
        public string ProductSize { get; set; }
        public string ProductType { get; set; }
        public Nullable<long> ProductPrice { get; set; }
    }
}
